### ISSUE TITLE
Tile URL parsing issue in latest version?

### ISSUE THREAD

**Issue by bothness** [stevage/vector-inspector#2]
Hi @stevage. Thanks for developing this really helpful tool

I have a set of vector tiles with URLs in the format https://example.com/tiles/v2/{z}/{x}/{y}.pbf . These had always read fine in previous version of Vector Inspector, but since the latest update, it seems to misread the "v2" element of the URL as part of the XYZ coordinates, and ends up generating invalid tile URLs, making the tool unusable.

**Comment by bothness** [comment]
If I'm reading your code correctly (I'm not very familiar with Vue apps), I'm guessing the issue is with the change to [this regex pattern](https://github.com/stevage/vector-inspector/blob/1ec7d91c02e131274b9fef7bc14ce0f2674bf775/src/App.vue#L106).

**Comment by stevage** [comment]
Ah, good to know someone is using it :)

I made the change because I wanted to support a site where the URL pattern doesn't have an extension: like `?tile=1/2/3`

Are you up for making a PR that can accommodate both these needs?

**Comment by stevage** [comment]
Oh, I think this works. Let me know if it doesn't fix it.

**Comment by bothness** [comment]
Thanks for responding so quickly. For some reason the URLs are now coming out like this, with a $1 in place of the first slash: `../tiles/v2$1{z}/{x}/{y}.pbf`

Re using the tool, a colleague introduced me to it. Previously I had either been using the inpspect mode on Maputnik, serving tiles locally with tileserver-gl (which has a build-in inspector mode), or opening individual tiles in QGIS to try to figure out the layers and features they had. Vector Inspector definitely makes this process quicker and easier in 90% of cases!

**Comment by stevage** [comment]
Sorry, I did something dumb. Fixed now?
